name: Bash Script Test

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up permissions
          run: |
            chmod +x ./scripts/*.sh
        
        - name: Run script
          run: |
            ./scripts/script.sh "dansbeerlist.txt"

        - name: Read from TXT file
          run: |
            ./scripts/readfile.sh "dansbeerlist.txt"
            
        - name: Compile and run
          run: |
            ./scripts/compileandrun.sh
        
        - name: Run script with args
          run: |
            ./scripts/echoargs.sh "poop" "arg2"